# Generated by Django 3.2.17 on 2023-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThyroidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=1000)),
                ('crc32', models.CharField(max_length=1000)),
            ],
        ),
    ]
