# Generated by Django 3.2.17 on 2023-02-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyroidimage',
            name='label',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterModelTable(
            name='thyroidimage',
            table='thyroid_image',
        ),
    ]
