# Generated by Django 3.2.17 on 2023-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyroid', '0002_auto_20230222_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thyroidimage',
            name='label',
            field=models.IntegerField(),
        ),
    ]
